### ISSUE TITLE
compute_irmsd_fast() only works on two chains

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/pdb2sql#76]
```
>>> ref = "ref.pdb"
>>> model = "model.pdb"
>>> sim = StructureSimilarity(model,ref)
>>> irmsd_fast = sim.compute_irmsd_fast()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lixue/tools/anaconda3/lib/python3.7/site-packages/pdb2sql/StructureSimilarity.py", line 277, in compute_irmsd_fast
    resData = self.compute_izone(cutoff, save_file=False)
  File "/home/lixue/tools/anaconda3/lib/python3.7/site-packages/pdb2sql/StructureSimilarity.py", line 328, in compute_izone
    'exactly two chains are needed for irmsd calculation but we found %d' % len(chains), chains)
ValueError: ('exactly two chains are needed for irmsd calculation but we found 5', ['A', 'B', 'C', 'D', 'E'])
```

[Archive.zip](https://github.com/DeepRank/pdb2sql/files/9086277/Archive.zip)

**Comment by LilySnow** [comment]
To solve this issue, I am planning to add an option `chain_pairs = ['D:E', 'AB:C']` to `compute_izone()`.

**Comment by NicoRenaud** [comment]
i've suggested to make a few change to Li's work see #80. This basically allows to use `get_contact_atoms` using multiple chains as : 
```python
db.get_contact_atoms(chain1='AB', chain2='C')
```

**Comment by NicoRenaud** [comment]
Related to PR #80  and #79
